name: Code Merge
on:
  workflow_dispatch:



jobs:
  generate-version-number:
    name: Generate Version Number
    runs-on: [ uk-digital-k8s-self-hosted ]
    container:
      image: 732440210582.dkr.ecr.eu-west-1.amazonaws.com/library/openjdk:jdk21-maven-3-9-6
      credentials:
        username: AWS
        password: ${{ secrets.AWS_ECR_PASSWORD }}
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Write Version to File
        run: |
          echo "v$(date "+%Y%m%d%H%M%S")" > version.txt  

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: version-artifact
          path: "version.txt"

  update-version:
    name: Increment Version in pom.xml
    runs-on: [ uk-digital-k8s-self-hosted ]
    needs: generate-version-number
    container:
      image: 732440210582.dkr.ecr.eu-west-1.amazonaws.com/library/openjdk:jdk21-maven-3-9-6
      credentials:
        username: AWS
        password: ${{ secrets.AWS_ECR_PASSWORD }}
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: version-artifact

      - name: Read Version from File
        id: versionNumber
        run: |
          version=$(cat version.txt)  
          echo "The version of pom.xml is: $version"
          eval echo "version=$version >> $GITHUB_OUTPUT"
      - name: Set new version in pom.xml
        run: |
          mvn versions:set -DnewVersion=${{ steps.versionNumber.outputs.version }} -DgenerateBackupPoms=false
      - name: Commit pom.xml
        run: |
          git config --global --add safe.directory "$(pwd)" 
          git config --global user.email "automationNoReply@ssnc.com"
          git config --global user.name "Github Automation"
          git add pom.xml
          git commit -m "Auto update version number in pom.xml"  
          git push origin HEAD  
