name: FSI Stage and Prod Workflow
on:
  workflow_dispatch:


jobs:
  create-pr-before-merge-into-main:  
    runs-on: ubuntu-latest 
    name: Create PR From Release to Main
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        
      - name: Create Pull Request  
        id: create_pr
        env:
           GH_TOKEN: ${{ github.token }}
        run: |  
          PR_URL=$(gh pr create --base main --head ${{ github.ref_name }} --title "[Automated] Create PR from  ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}" --body "Please review this PR.")
          PR_NUMBER=$(echo "$PR_URL" | sed 's/.*\///')
          eval echo "pr_number=$PR_NUMBER >> $GITHUB_OUTPUT"
          eval echo "pr_url=$PR_URL >> $GITHUB_OUTPUT"
          gh pr status --conflict-status

      # - name: Check PR Merge Status
      #   id: pr_merge_status
      #   run: |

      #     gh pr status --conflict-status

