name: FSI Stage and Prod Workflow
on:
  workflow_dispatch:


jobs:
  create-pr-before-merge-into-main:  
    runs-on: ubuntu-latest 
    name: Create PR From Release to Main
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        
      - name: Create Pull Request  
        id: create_pr
        env:
           GH_TOKEN: ${{ github.token }}
        run: |  
          PR_URL=$(gh pr create --base main --head ${{ github.ref_name }} --title "[Automated] Create PR from  ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}" --body "Please review this PR.")
          PR_NUMBER=$(echo "$PR_URL" | sed 's/.*\///')
          eval echo "pr_number=$PR_NUMBER >> $GITHUB_OUTPUT"
          eval echo "pr_url=$PR_URL >> $GITHUB_OUTPUT"

      - name: Check PR Merge Status
        id: pr_merge_status
        run: |
          PR_URL=${{ steps.create_pr.outputs.pr_url }}

          PR_RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $PR_URL)

          # echo $PR_RESPONSE
          # # Check if request was successful
          # if [ $? -ne 0 ]; then
          #   echo "Failed to fetch PR details."
          #   exit 1
          # fi

          # Extract merge status
          MERGED=$(echo "$PR_RESPONSE" | jq -r '.merged')

          # Output merge status
          if [ "$MERGED" = "true" ]; then
            echo "Pull Request is merged."
          else
            echo "Pull Request is not merged."
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
