name: FSI Stage and Prod Workflow
on:
  workflow_dispatch:


jobs:
  create-pr-before-merge-into-main:  
    runs-on: ubuntu-latest 
    name: Create PR From Release to Main
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        
      - name: Create Pull Request  
        id: create_pr
        env:
           GH_TOKEN: ${{ github.token }}
        run: |  
          PR_URL=$(gh pr create --base main --head ${{ github.ref_name }} --title "[Automated] Create PR from  ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}" --body "Please review this PR.")
          echo "PR url is $PR_URL"
          PR_NUMBER=$(echo "$PR_URL" | sed 's/.*\///')
          

          
          PR_STATUS=$(gh pr status --conflict-status --json url,number,state,mergeable)
          echo "$PR_STATUS"
          # Parse JSON and extract mergeable status
          MERGEABLE_STATUS=$(echo "$PR_STATUS" | jq '.currentBranch.mergeable')
          echo "Mergeable status: $MERGEABLE_STATUS"

          
          
          if [ "$MERGEABLE_STATUS" = "CONFLICTING" ]; then
            echo "PR has conflicts. Cannot merge automatically."
          elif [ "$MERGEABLE_STATUS" = "MERGEABLE" ]; then
            gh pr merge $PR_NUMBER --merge
            echo "PR has been automatically merged."
          else
            echo "Unexpected mergeable status: $MERGEABLE_STATUS"
          fi
          


