name: FSI Stage and Prod Workflow
on:
  workflow_dispatch:


jobs:
  create-pr-before-merge-into-main:  
    runs-on: ubuntu-latest 
    name: Create PR From Release to Main
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        
      - name: Create Pull Request  
        id: create_pr
        env:
           GH_TOKEN: ${{ github.token }}
        run: |  
          PR_URL=$(gh pr create --base main --head ${{ github.ref_name }} --title "[Automated] Create PR from  ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}" --body "Please review this PR.")
          echo "PR url is $PR_URL"
          PR_NUMBER=$(echo "$PR_URL" | sed 's/.*\///')
          # eval echo "pr_number=$PR_NUMBER >> $GITHUB_OUTPUT"
          # eval echo "pr_url=$PR_URL >> $GITHUB_OUTPUT"
          PR_STATUS=$(gh pr status --conflict-status --json url,number,state,mergeable)
          echo "$PR_STATUS"
          # Parse JSON and extract mergeable status
          MERGEABLE_STATUS=$(echo "$PR_STATUS" | jq '.currentBranch[0].mergeable')
          PR_STATUS=$(echo "$PR_STATUS" | jq -r '.currentBranch[0].state')
          echo "Mergeable status: $MERGEABLE_STATUS"
          echo "PR status: $PR_STATUS"


