name: Create release from latest tag
on:
  workflow_dispatch:
  
jobs:  
  Check-pr-status:  
    runs-on: ubuntu-latest  
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Git Tag
        id: create_tag
        run: |
          git config --global --add safe.directory "$(pwd)" 
          git config --global user.email "automationNoReply@ssnc.com"
          git config --global user.name "Github Automation"       
          git tag -a v1234 -m "Version v1234"  
          git push origin v1234
        
      - name: Get latest tag
        id: latest_tag
        run: |
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=tag::$TAG"      

      - name: Check if release exists  
        id: check_release  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: |  
          RELEASE_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.latest_tag.outputs.tag }}"  
            
          curl -sL $RELEASE_URL -o /dev/null -w "%{http_code}"  
            
          if [ $? -eq 22 ]; then  
            eval echo "exists=false >> $GITHUB_OUTPUT"
          else  
             eval echo "exists=true >> $GITHUB_OUTPUT"
          fi  
          
      - name: Create Release
        if: steps.check_release.outputs.exists == 'false'  
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.latest_tag.outputs.tag }}
          release_name: ${{ steps.latest_tag.outputs.tag }}
          body: |
            Github Automation
          draft: false
          prerelease: false         
