name: Merge Release to main

on:
  push:
    branches:
      - release

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge release into main
        run: |
          # Fetch the latest changes
          git fetch --prune
          
          # Get the current SHA of main branch
          MAIN_SHA=$(git rev-parse main)

          # Get the current SHA of release branch
          release_SHA=$(git rev-parse release)

          # Create a merge commit
          MERGE_COMMIT=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"base\":\"main\",\"head\":\"release\",\"commit_message\":\"Merge release into main\"}" \
            https://api.github.com/repos/${{ github.repository }}/merges | jq -r .sha)

          # Check if the merge was successful
          if [ -n "$MERGE_COMMIT" ]; then
            echo "release branch merged into main successfully."
            
            # Push the merge commit to main
            git push origin "HEAD:refs/heads/main"
          else
            echo "Failed to merge release branch into main."
            exit 1
          fi
