name: reuse
on:
  workflow_call:
    inputs:
      REGISTRY_URL:
        default: "www.baidu.com"
        required: true
        type: string
      REGISTRY_IMAGE:
        required: true
        type: string
      APP_NAME:
        required: true
        type: string

jobs:
  deploy:
    environment: ${{ inputs.ENV_APPROVAL_NAME }}
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: validate-variables
        run: |
            echo "${{ inputs.REGISTRY_URL }}"
            echo "${{ inputs.REGISTRY_IMAGE }}"
            echo "${{ inputs.APP_NAME }}"
        shell: bash
