name: shareValue
on:
  workflow_dispatch:

env:
  TASK_ID: ${{ github.run_id }}-${{ github.run_number }}
  VERSION_NUMBER: ""

jobs:

  generate-version-number:
    name: Generate Version Number
    runs-on: ubuntu-latest
    steps:
      - name: Write Version to File
        run: |
          VERSION="v1.0.0-${{ github.run_number }}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Generated version: $VERSION"


  create-tag:
    name: Create New Tag
    runs-on: ubuntu-latest
    needs: generate-version-number
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Create Git Tag
        id: create_tag
        run: |
          echo "Generated version: $VERSION"
          git config --global --add safe.directory "$(pwd)" 
          git config --global user.email "automationNoReply@ssnc.com"
          git config --global user.name "Github Automation"       
          git tag -a $VERSION -m "Version $VERSION"  
          git push origin $VERSION
          
          
  deploy-to-uk-fsi-prod:
    name: Deploy to uk fsi prod
    runs-on: ubuntu-latest
    needs: create-tag
    steps:  
      - name: Checkout  
        uses: actions/checkout@v3
        with:  
          fetch-depth: 0 
          
      - name: Initiate Argo CD (Prod)
        run: |  
          echo "Because there is no lnp-investments in k8s-apps-fsi-uk,So this step is just for test."     
          echo "$VERSION"
          

             
