name: shareValue
on:
  workflow_dispatch:
    inputs:
      chosen-runs:
        required: true
        type: choice
        options:
        - ubuntu-latest
      
jobs:
  generate-version-number:
    name: Generate Version Number
    runs-on:  [ "${{ inputs.chosen-runs }}"]
    outputs:
      version: ${{ steps.step1.outputs.version }}
    steps:
      - id: step1
        run: |
          VERSION="v1.0.0-${{ github.run_number }}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  create-tag:
    name: Create New Tag
    runs-on: [ "${{ inputs.chosen-runs }}"]
    needs: generate-version-number
    steps:
       
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Create Git Tag
        id: create_tag

        run: |
          echo "Generated version: ${{ needs.generate-version-number.outputs.version}}"
          # git config --global --add safe.directory "$(pwd)" 
          # git config --global user.email "automationNoReply@ssnc.com"
          # git config --global user.name "Github Automation"       
          # git tag -a $version -m "Version $VERSION"  
          # git push origin $version
          
          
  deploy-to-uk-fsi-prod:
    name: Deploy to uk fsi prod
    runs-on: [ "${{ inputs.chosen-runs }}"]
    needs: create-tag
    steps:  
      - name: Checkout  
        uses: actions/checkout@v3
        with:  
          fetch-depth: 0 
          
      - name: Initiate Argo CD (Prod)
        run: |  
          echo "Because there is no lnp-investments in k8s-apps-fsi-uk,So this step is just for test."     
          echo "${{needs.create-tag.outputs.version}}"
          

             
