name: shareValue
on:
  workflow_dispatch:
    
jobs:
  generate-version-number:
    name: Generate Version Number
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step1.outputs.version }}
    steps:
      - id: step1
        run: |
          VERSION="v1.0.2-${{ github.run_number }}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  create-tag:
    name: Create New Tag
    runs-on: ubuntu-latest
    needs: generate-version-number
    outputs:
      version: ${{ needs.generate-version-number.outputs.version}}
    steps:
       
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Create Git Tag
        id: create_tag

        run: |
          echo "Generated version: ${{ needs.generate-version-number.outputs.version}}"
          
          
  deploy-to-uk-fsi-stage:
    name: Initiate ArgoCD - UK FSI Stage
    needs: [create-tag]
    uses: github.com/sherminMing/code-merge/.github/workflows/resue.yaml@main
    with:
      REGISTRY_URL: kea/lnp-investments
      REGISTRY_IMAGE: lnp-investments
      APP_NAME: fsi-uk-kea-stage
          

             
