name: shareValue
on:
  workflow_dispatch:
env:
  APP_NAME: animals
jobs:
  generate-version-number:
    name: Generate Version Number
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step1.outputs.version }}
    steps:
      - name: step1
        id: step1
        run: |
          VERSION="v1.0.2-${{ github.run_number }}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "App name: ${{ env.APP_NAME }}"

  create-tag:
    name: Create New Tag
    runs-on: ubuntu-latest
    needs: generate-version-number
    outputs:
      version: ${{ needs.generate-version-number.outputs.version}}
    steps:
       
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Create Git Tag
        id: create_tag

        run: |
          echo "Generated version: ${{ needs.generate-version-number.outputs.version }}"
          echo "App name: ${{ env.APP_NAME }}"
          
          
  deploy:
    name: Initiate 
    needs: [create-tag]
    uses: sherminMing/code-merge/.github/workflows/reuse.yaml@main
    with:
      REGISTRY_URL: atp/animals
      REGISTRY_IMAGE: animals
      APP_NAME: Hello
          

             
