name: shareValue
on:
  workflow_dispatch:
    
jobs:
  generate-version-number:
    name: Generate Version Number
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step1.outputs.version }}
    steps:
      - id: step1
        run: |
          ${{ env.version }}="v1.0.2-${{ github.run_number }}"
          echo "version=${{ env.version }}" >> "$GITHUB_OUTPUT"

  create-tag:
    name: Create New Tag
    runs-on: ubuntu-latest
    needs: generate-version-number
    outputs:
      version: ${{ needs.generate-version-number.outputs.version}}
    steps:
       
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Create Git Tag
        id: create_tag

        run: |
          echo "Generated version: ${{ env.version}}"
          git config --global --add safe.directory "$(pwd)" 
          git config --global user.email "automationNoReply@ssnc.com"
          git config --global user.name "Github Automation"       
          git tag -a ${{ needs.generate-version-number.outputs.version}} -m "Version ${{ needs.generate-version-number.outputs.version}}"  
          git push origin ${{ needs.generate-version-number.outputs.version}}
          
          
  deploy-to-uk-fsi-prod:
    name: Deploy to uk fsi prod
    runs-on: ubuntu-latest
    needs: [create-tag,generate-version-number]
    steps:  
      - name: Checkout  
        uses: actions/checkout@v3
        with:  
          fetch-depth: 0 
          
      - name: Initiate Argo CD (Prod)
        run: |  
          echo "Because there is no lnp-investments in k8s-apps-fsi-uk,So this step is just for test."     
          echo "${{needs.generate-version-number.outputs.version}}"
          

             
